import "./globals.css";
<<<<<<< HEAD
import { Inter, Geist } from "next/font/google";
import { ReactQueryClientProvider } from "@/utils/react-query";
import Navbar from "@/components/navbar";
import Footer from "@/components/footer";
import { cn } from "@/lib/utils";

const geist = Geist({ subsets: ["latin"], variable: "--font-sans" });
=======
import { Inter } from "next/font/google";
import { ReactQueryClientProvider } from "@/utils/react-query";
>>>>>>> origin/main

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
<<<<<<< HEAD
  title: "Archery Club @ UCR",
  description: "Archery Club at UCR",
=======
  title: "Create Next App",
  description: "Generated by create next app",
>>>>>>> origin/main
};

type LayoutProps = {
  children: React.ReactNode;
};

export default function RootLayout({ children }: LayoutProps) {
  return (
<<<<<<< HEAD
    <html lang="en" className={cn("font-sans", geist.variable)}>
      <body className={inter.className}>
        <ReactQueryClientProvider>
          <Navbar />

          {children}
          <Footer />
        </ReactQueryClientProvider>
=======
    <html lang="en">
      <body className={inter.className}>
        <ReactQueryClientProvider>{children}</ReactQueryClientProvider>
>>>>>>> origin/main
      </body>
    </html>
  );
}
